print("1-ое задание")
print("")
print("Введите любую строку:")
my_string = input()
print("Количество символов:", len(my_string))
print("")
print("2-ое задание")
print("")
print("Введите любую строку:")
my_string = input()
print(f"Строка в верхнем регистре: {my_string.upper()}.")
print(f"Строка в нижнем регистре:, {my_string.lower()}.")
print(f"Строка без пробелов: {my_string.replace(" ", "")}.")
print(f"Первая буква строки: {my_string[0]}.")
print(f"Последняя буква строки: {my_string[-1]}.")